CREATE OR REPLACE FUNCTION insert_sku() RETURNS TRIGGER AS $$
DECLARE 
  tokens CHAR(62) := '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  tokens_length INT := length(tokens); 
  num BIGINT;
  remainder INT;
  result CHAR(6) := '';
  pattern CHAR(6) := '000000';
BEGIN
  IF NEW.sku is NULL THEN
    num := NEW.id;
    WHILE(TRUE) LOOP
      IF (num = 0) THEN
        exit;
      END IF;
      remainder = num % tokens_length;
      result := substring(tokens FROM remainder + 1 FOR 1) || result;
      num := num / tokens_length;
    END LOOP;
    NEW.sku = substring(pattern FROM 1 FOR length(pattern) - length(result) )  || result;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TABLE tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(20),
  sku CHAR(6) UNIQUE
);
CREATE TRIGGER trigger_insert_tests_sku 
  BEFORE INSERT 
  ON tests 
  FOR EACH ROW
    EXECUTE PROCEDURE insert_sku();
